//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_interact : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean isTriggerClicked
        {
            get
            {
                return SteamVR_Actions.interact_isTriggerClicked;
            }
        }
        
        public virtual SteamVR_Action_Boolean isGripClicked
        {
            get
            {
                return SteamVR_Actions.interact_isGripClicked;
            }
        }
        
        public virtual SteamVR_Action_Boolean isMenuClicked
        {
            get
            {
                return SteamVR_Actions.interact_isMenuClicked;
            }
        }
        
        public virtual SteamVR_Action_Boolean isPadClicked
        {
            get
            {
                return SteamVR_Actions.interact_isPadClicked;
            }
        }
        
        public virtual SteamVR_Action_Vector2 PadPose
        {
            get
            {
                return SteamVR_Actions.interact_PadPose;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.interact_Pose;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerPressValue
        {
            get
            {
                return SteamVR_Actions.interact_TriggerPressValue;
            }
        }
        
        public virtual SteamVR_Action_Boolean isPadTouched
        {
            get
            {
                return SteamVR_Actions.interact_isPadTouched;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadNorth
        {
            get
            {
                return SteamVR_Actions.interact_PadNorth;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadSouth
        {
            get
            {
                return SteamVR_Actions.interact_PadSouth;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadEast
        {
            get
            {
                return SteamVR_Actions.interact_PadEast;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadWest
        {
            get
            {
                return SteamVR_Actions.interact_PadWest;
            }
        }
        
        public virtual SteamVR_Action_Vibration ControllerVibration
        {
            get
            {
                return SteamVR_Actions.interact_ControllerVibration;
            }
        }
    }
}
