//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_default_InteractUI;
        
        private static SteamVR_Action_Boolean p_default_Teleport;
        
        private static SteamVR_Action_Boolean p_default_GrabPinch;
        
        private static SteamVR_Action_Boolean p_default_GrabGrip;
        
        private static SteamVR_Action_Pose p_default_Pose;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonRightHand;
        
        private static SteamVR_Action_Single p_default_Squeeze;
        
        private static SteamVR_Action_Boolean p_default_HeadsetOnHead;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        private static SteamVR_Action_Boolean p_interact_isTriggerClicked;
        
        private static SteamVR_Action_Boolean p_interact_isGripClicked;
        
        private static SteamVR_Action_Boolean p_interact_isMenuClicked;
        
        private static SteamVR_Action_Boolean p_interact_isPadClicked;
        
        private static SteamVR_Action_Vector2 p_interact_PadPose;
        
        private static SteamVR_Action_Pose p_interact_Pose;
        
        private static SteamVR_Action_Single p_interact_TriggerPressValue;
        
        private static SteamVR_Action_Boolean p_interact_isPadTouched;
        
        private static SteamVR_Action_Boolean p_interact_PadNorth;
        
        private static SteamVR_Action_Boolean p_interact_PadSouth;
        
        private static SteamVR_Action_Boolean p_interact_PadEast;
        
        private static SteamVR_Action_Boolean p_interact_PadWest;
        
        private static SteamVR_Action_Vibration p_interact_ControllerVibration;
        
        public static SteamVR_Action_Boolean default_InteractUI
        {
            get
            {
                return SteamVR_Actions.p_default_InteractUI.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Teleport
        {
            get
            {
                return SteamVR_Actions.p_default_Teleport.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabPinch
        {
            get
            {
                return SteamVR_Actions.p_default_GrabPinch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabGrip
        {
            get
            {
                return SteamVR_Actions.p_default_GrabGrip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Single default_Squeeze
        {
            get
            {
                return SteamVR_Actions.p_default_Squeeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean default_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_default_HeadsetOnHead.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Boolean interact_isTriggerClicked
        {
            get
            {
                return SteamVR_Actions.p_interact_isTriggerClicked.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean interact_isGripClicked
        {
            get
            {
                return SteamVR_Actions.p_interact_isGripClicked.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean interact_isMenuClicked
        {
            get
            {
                return SteamVR_Actions.p_interact_isMenuClicked.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean interact_isPadClicked
        {
            get
            {
                return SteamVR_Actions.p_interact_isPadClicked.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 interact_PadPose
        {
            get
            {
                return SteamVR_Actions.p_interact_PadPose.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Pose interact_Pose
        {
            get
            {
                return SteamVR_Actions.p_interact_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Single interact_TriggerPressValue
        {
            get
            {
                return SteamVR_Actions.p_interact_TriggerPressValue.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean interact_isPadTouched
        {
            get
            {
                return SteamVR_Actions.p_interact_isPadTouched.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean interact_PadNorth
        {
            get
            {
                return SteamVR_Actions.p_interact_PadNorth.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean interact_PadSouth
        {
            get
            {
                return SteamVR_Actions.p_interact_PadSouth.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean interact_PadEast
        {
            get
            {
                return SteamVR_Actions.p_interact_PadEast.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean interact_PadWest
        {
            get
            {
                return SteamVR_Actions.p_interact_PadWest.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration interact_ControllerVibration
        {
            get
            {
                return SteamVR_Actions.p_interact_ControllerVibration.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.interact_isTriggerClicked,
                    SteamVR_Actions.interact_isGripClicked,
                    SteamVR_Actions.interact_isMenuClicked,
                    SteamVR_Actions.interact_isPadClicked,
                    SteamVR_Actions.interact_PadPose,
                    SteamVR_Actions.interact_Pose,
                    SteamVR_Actions.interact_TriggerPressValue,
                    SteamVR_Actions.interact_isPadTouched,
                    SteamVR_Actions.interact_PadNorth,
                    SteamVR_Actions.interact_PadSouth,
                    SteamVR_Actions.interact_PadEast,
                    SteamVR_Actions.interact_PadWest,
                    SteamVR_Actions.interact_ControllerVibration};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.interact_isTriggerClicked,
                    SteamVR_Actions.interact_isGripClicked,
                    SteamVR_Actions.interact_isMenuClicked,
                    SteamVR_Actions.interact_isPadClicked,
                    SteamVR_Actions.interact_PadPose,
                    SteamVR_Actions.interact_Pose,
                    SteamVR_Actions.interact_TriggerPressValue,
                    SteamVR_Actions.interact_isPadTouched,
                    SteamVR_Actions.interact_PadNorth,
                    SteamVR_Actions.interact_PadSouth,
                    SteamVR_Actions.interact_PadEast,
                    SteamVR_Actions.interact_PadWest};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.interact_ControllerVibration};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.interact_ControllerVibration};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.interact_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.interact_isTriggerClicked,
                    SteamVR_Actions.interact_isGripClicked,
                    SteamVR_Actions.interact_isMenuClicked,
                    SteamVR_Actions.interact_isPadClicked,
                    SteamVR_Actions.interact_isPadTouched,
                    SteamVR_Actions.interact_PadNorth,
                    SteamVR_Actions.interact_PadSouth,
                    SteamVR_Actions.interact_PadEast,
                    SteamVR_Actions.interact_PadWest};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.interact_TriggerPressValue};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.interact_PadPose};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.interact_isTriggerClicked,
                    SteamVR_Actions.interact_isGripClicked,
                    SteamVR_Actions.interact_isMenuClicked,
                    SteamVR_Actions.interact_isPadClicked,
                    SteamVR_Actions.interact_PadPose,
                    SteamVR_Actions.interact_TriggerPressValue,
                    SteamVR_Actions.interact_isPadTouched,
                    SteamVR_Actions.interact_PadNorth,
                    SteamVR_Actions.interact_PadSouth,
                    SteamVR_Actions.interact_PadEast,
                    SteamVR_Actions.interact_PadWest};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_InteractUI = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/InteractUI")));
            SteamVR_Actions.p_default_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Teleport")));
            SteamVR_Actions.p_default_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabPinch")));
            SteamVR_Actions.p_default_GrabGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabGrip")));
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonLeftHand")));
            SteamVR_Actions.p_default_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonRightHand")));
            SteamVR_Actions.p_default_Squeeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default/in/Squeeze")));
            SteamVR_Actions.p_default_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/HeadsetOnHead")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
            SteamVR_Actions.p_interact_isTriggerClicked = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/interact/in/isTriggerClicked")));
            SteamVR_Actions.p_interact_isGripClicked = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/interact/in/isGripClicked")));
            SteamVR_Actions.p_interact_isMenuClicked = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/interact/in/isMenuClicked")));
            SteamVR_Actions.p_interact_isPadClicked = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/interact/in/isPadClicked")));
            SteamVR_Actions.p_interact_PadPose = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/interact/in/PadPose")));
            SteamVR_Actions.p_interact_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/interact/in/Pose")));
            SteamVR_Actions.p_interact_TriggerPressValue = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/interact/in/TriggerPressValue")));
            SteamVR_Actions.p_interact_isPadTouched = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/interact/in/isPadTouched")));
            SteamVR_Actions.p_interact_PadNorth = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/interact/in/PadNorth")));
            SteamVR_Actions.p_interact_PadSouth = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/interact/in/PadSouth")));
            SteamVR_Actions.p_interact_PadEast = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/interact/in/PadEast")));
            SteamVR_Actions.p_interact_PadWest = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/interact/in/PadWest")));
            SteamVR_Actions.p_interact_ControllerVibration = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/interact/out/ControllerVibration")));
        }
    }
}
